backend:
  name: git-gateway
  branch: brandon-changes
site_url: https://getlavanda.com
logo_url: https://raw.githubusercontent.com/larpo1/lavanda-blog/master/static/img/lavanda-logo.svg?sanitize=true
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow  
collections:

  - name: "feature-pages"
    label: "Feature Pages"
    label_singular: "Feature Page"
    folder: "src/pages/features"
    create: true
    slug: "{{slug}}"
    fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "feature-page"}
          - {label: "Feature Title", name: "title", widget: "string"}
          - label: 'Sections'
            label_singular: "Section"
            name: 'sections'
            widget: 'list'
            types:
              - label: 'Hero'
                name: 'hero'
                widget: code


              # - label: 'Testimonial Section'
              #   name: 'testimonials'
              #   widget: object
              #   fields: 
              #     - { label: Testimonials, name: testimonials, widget: relation, collection: testimonials, searchFields: ["title"], valueField: "title", multiple: true, required: false}

              # - label: 'Benefits Grid'
              #   name: 'benefits'
              #   widget: object
              #   fields:
              #     - { label: Header, name: header, widget: string, default: 'Some Pretty Cool Benefits' }
              #     - label: Benefits
              #       name: benefits
              #       widget: list
              #       fields: 
              #         - { label: Icon, name: icon, widget: image, default: "/ad8a3f95-a846-42b5-aa5b-27020d8d69f2"}
              #         - { label: Blurb, name: blurb, widget: string }

              # - label: 'Spotlight'
              #   name: 'spotlight'
              #   widget: object
              #   fields:
              #     - { label: Header, name: header, widget: string, default: 'Spotlight' }
              #     - { label: Template, name: template, widget: string, default: 'spotlight.html' }
              #     - { label: Text, name: text, widget: text, default: 'Hello World' }
    # fields:
    #   - {label: "Template Key", name: "templateKey", widget: "hidden", default: "feature-page"}
    #   - {label: "Feature Title", name: "title", widget: "string"}
    #   - label: 'Sections'
    #     label_singular: "Section"
    #     name: 'sections'
    #     widget: 'list'
    #     types:
    #       - label: 'Hero'
    #         name: 'hero'
    #         widget: object
    #         fields: 
    #           - { label: Heros, name: hero, widget: relation, collection: heros, searchFields: ["title"], valueField: "title", required: false}

    #       - label: 'Testimonial Section'
    #         name: 'testimonials'
    #         widget: object
    #         fields: 
    #           - { label: Testimonials, name: testimonials, widget: relation, collection: testimonials, searchFields: ["title"], valueField: "title", multiple: true, required: false}

    #       - label: 'Benefits Grid'
    #         name: 'benefits'
    #         widget: object
    #         fields:
    #           - { label: Header, name: header, widget: string, default: 'Some Pretty Cool Benefits' }
    #           - label: Benefits
    #             name: benefits
    #             widget: list
    #             fields: 
    #               - { label: Icon, name: icon, widget: image, default: "/ad8a3f95-a846-42b5-aa5b-27020d8d69f2"}
    #               - { label: Blurb, name: blurb, widget: string }

    #       - label: 'Spotlight'
    #         name: 'spotlight'
    #         widget: object
    #         fields:
    #           - { label: Header, name: header, widget: string, default: 'Spotlight' }
    #           - { label: Template, name: template, widget: string, default: 'spotlight.html' }
    #           - { label: Text, name: text, widget: text, default: 'Hello World' }


  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "terms"
    label: "Terms"
    folder: "src/pages/terms"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "terms"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "heros"
    label: "Heros"
    label_singular: "Hero"
    folder: "src/content/heros"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "heros"}
      - {label: "H1", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Background Image", name: "backgroundImage", widget: "image"}
      - {label: "Foreground Image", name: "foregroundImage", widget: "image"}

  - name: "testimonials"
    label: "Testimonials"
    label_singular: "Testimonial"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "testimonials"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author Image", name: "image", widget: "image"}
      - {label: "Testimonial", name: "testimonial", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
